### PR TITLE
Optional RTEMS shell access

### PR DESCRIPTION
**Pull request by Laymer**
## Clean PR for #58 

Possible setups in `grisp/grisp_base/files/grisp.ini.mustache` :  

1. Erlang shell

- Default is Erlang shell if no configuration is provided
- Also possible through : 
```
 [erlang]
 args = erl.rtems -- -mode embedded <rest of emulator flags...>
 shell=erlang
```

2. RTEMS shell :
```
RTEMS shell access should be done with
additional emulator flags : 

 [erlang]
 args = erl.rtems -- -mode embedded -noshell -noinput <rest of emulator flags...>
 shell=rtems
```

3. No shell :
```
 If no shell is necessary, the following can be
 configured in the grisp.ini.mustache file :

 [erlang]
 args = erl.rtems -- -mode embedded -noshell -noinput <rest of emulator flags...>
 shell=none
```

### CODE REVIEW

**Review by peerst — APPROVED** [review]
Looks good to me, we should merge this

**Comment by sylane** [comment]
This PR has been redone in https://github.com/grisp/grisp/pull/125

**Comment by sylane** [comment]
https://github.com/grisp/grisp/pull/125 got merged into master

**Comment by sylane** [comment]
https://github.com/grisp/grisp/pull/125 got merged into master and cover this PR

**Pull request closed without merging**
