### PR TITLE
Added a very first version of pmod_gps

### PR DESCRIPTION
**Pull request by aytchell**
This new device driver can fetch GPS NMEA sentences from a
'Digilent PmodGPS'.
This first version was shamelessly copied and adapted from
pmod_maxsonar.erl

It listens to the stream of incoming NMEA sentences and stores the
latest version of each of the four supported sentences (GGA, GSA, GSV,
RMC and VTG).

You can get the latest sentence by calling e.g. pmod_gps:get(gga).
The driver does not split up and further analyse the received sentences
- this could be a good starting point for extending the driver.

PS: This driver was coded during a GRiSP tutorial on 06.12.2018
PPS: Beware! I have no clue of erlang, so please proof-read ;-)

### CODE REVIEW

**Comment by aytchell** [comment]
Example output:

> (robot@hle_grisp_board)4> pmod_gps:get(gga).
<<"$GPGGA,010629.800,,,,,0,0,,,M,,M,,*4C\n">>
(robot@hle_grisp_board)5> pmod_gps:get(gsa).
<<"$GPGSA,A,1,,,,,,,,,,,,,,,*1E\n">>
(robot@hle_grisp_board)6> pmod_gps:get(gsv).
<<"$GPGSV,1,1,00*79\n">>
(robot@hle_grisp_board)7> pmod_gps:get(rmc).
<<"$GPRMC,010723.800,V,,,,,0.00,0.00,060180,,,N*4D\n">>
(robot@hle_grisp_board)8> pmod_gps:get(vtg).
<<"$GPVTG,0.00,T,,M,0.00,N,0.00,K,N*32\n">>

**Comment by aytchell** [comment]
Read the spec and found out that only one satellite is visible (the '1' in GPGSA) so the chip couldn't calculate the position ('V' in GPRMC says 'receiver warning').
GPGSA and GPRMC will carry lat/long if more satellites are visible.

**Comment by aytchell** [comment]
One (maybe silly) question: Is is possible to match against <<"$GPGGA",_/binary>> ?
It compiles but I don't have the target available any longer ...

**Comment by peerst** [comment]
@aytchell are you interested in continuing the work on this?  We might have some NMEA parsing code that we could contribute.

**Comment by peerst** [comment]
@aytchell could you maybe rebase your PR to master so our new CI can pick it up, then we can merge it and base further work on it

**Comment by aytchell** [comment]
Rebased code to latest master and opened a new PR --> #57

**Comment by aytchell** [comment]
@peerst I'm sorry but I don't find any time atm for this work

**Comment by peerst** [comment]
No worries and thanks for rebasing!

**Pull request closed without merging**
