### PR TITLE
Ensure the pthread default policy is SCHED_RR

### PR DESCRIPTION
**Pull request by sylane**

### CODE REVIEW

**Comment by sylane** [comment]
I made it like this so it was simpler to test with or without pthread wrapper... could be removed if you want.

**Comment by nextl00p** [comment]
What's the state of this?

**Comment by sylane** [comment]
I forgot about that! @eproxus this could explain why a lot of IO made the led stop blinking...

**Comment by sylane** [comment]
This need to be merged, probably approved by @peerst

**Comment by peerst** [comment]
I still don’t see that value in the THREADED_ERLANG_INIT conditionals.  Either it works then we merge it without them or it works not then we shouldn’t merge it anyway.

While you are at it the #ifdef __rtems__ is obsolete now and should be removed together with its #else clause (at the end of the file)

**Comment by nextl00p** [comment]
I removed the `#ifdef rtems`.

@peerst not sure what you mean with the `THREADED_ERLANG_INIT` conditionals in your last comment.

**Comment by sylane** [comment]
I suppose it is my fault to amend the commit so you didn't know I actually made the changes already...

**Comment by eproxus** [comment]
@peerst @sylane @nextl00p Status? Can we merge this?

**Comment by peerst** [comment]
Please merge

**Pull request merged**
