### PR TITLE
Add Feature wireless ad hoc network mode

### PR DESCRIPTION
**Pull request by Laymer**
### EDIT : prefixes have been added
Provide possibility to setup ad hoc wireless networks by providing arguments in the `grisp.ini` configuration file.  The parameters are :    
- `wlan_mode` : if set to "adhoc", the ifconfig command will be given adhoc mode as operation mode 
- `wlan_adhocname` : SSID of the ad hoc network 
- `wlan_channel` : the operating channel in the 2.4GHz band 
- `wlan_ip_netmask` : subnet mask for the assigned IP address
- `wlan_ip_self` : assigned IP address used for wireless configurations
- `wlan_hostname` : hostname used for wireless configurations

### EDIT N°2
The standard `ip_self` and `hostname` attributes have been left independent from the `wlan_`-prefixed parameters, so that the standard configuration is identical and if a Pmod Ethernet module is added in the future, these attributes could be used for that purpose for example.

### CODE REVIEW

**Comment by eproxus** [comment]
I'm wondering if it would make sense to prefix the WLAN specific configuration attributes with `wlan_` such as `wlan_channel` etc. in case we add other similar attributes for other network types later...

**Comment by eproxus** [comment]
@Laymer sorry to be a bother, but could you revert the white space changes on lines which you haven't modified? That would make the diff much smaller and easier to review

**Comment by eproxus** [comment]
@Laymer May well be. We've had problems of mixed tabs and spaces before and perhaps not everything is cleaned out.  Sorry for the mess

**Comment by Laymer** [comment]
@eproxus No worries, I was just asking to make sure. I will push a quickfix in no time.

**Comment by Laymer** [comment]
@eproxus I have reverted all the whitespace changes I could spot, I hope it makes it easier to review the code itself. Please feel free to let me know if there are some additional changes I should make.

**Comment by eproxus** [comment]
@Laymer That looks simple and nice, thank you!

@peerst @sylane Can you review this please?

**Comment by Laymer** [comment]
@eproxus Glad if I can help ! Thank you for taking the time to review all.

**Comment by peerst** [comment]
Why is there a `wlan_hostame` in addition to the normal `hostname` and what is their relationship?

**Comment by Laymer** [comment]
@peerst I have tried to comply with the following :

> I'm wondering if it would make sense to prefix the WLAN specific configuration attributes with `wlan_` such as `wlan_channel` etc. in case we add other similar attributes for other network types later...

But the original `hostname` has not been modified at all so I think that there is no relationship between them. I also imagined that maybe it would be possible in the future to use the Pmod Ethernet module, so two different hostnames could coexist. But this was a pure assumption and I have left the default `hostname` just in case removing it would introduce conflicts.

**Comment by peerst** [comment]
But wouldn’t they be set to the same name 100% of the uses? If I have a machine with multiple network interfaces it still has one hostname.  Or is there a reason to have a different hostname from the wlan_hostname?

Wouldn’t it make sense to just huse the hostname for wlan?

**Comment by eproxus** [comment]
This feature needs documentation, either in the README or on the wiki.

**Comment by Laymer** [comment]
@eproxus This is something I will definitely work on, as it is a hard requirement for me to make it usable and configurable. Now that this PR is merged I could open another one for the docs and write down a wiki page for it if that is okay for GRiSP? 🙂

**Comment by eproxus** [comment]
@Laymer Sounds good!

**Pull request merged**
