### PR TITLE
Add Missing SPI pins

### PR DESCRIPTION
**Pull request by Theuns-Botha**

### CODE REVIEW

**Comment by peerst** [comment]
I see many unrelated commits here. I think something went wrong creating this PR maybe?

Also some tests are failing probably because this PR is not rebased to our latest master and the CI system needs stuff from it

**Comment by Theuns-Botha** [comment]
Those commits are all things I did for grisp before. I will try figure out what is going on tonight.

**Comment by peerst** [comment]
The failing tests are not an issue, these are expected for PRs which contain changes to C code, since they are testing if downloadable prebuilt OTP works (which it can't and shouldn't since the C code changed).  So these are expected failures which we don't deal with correctly in the CI

**Comment by Theuns-Botha** [comment]
No longer relevant

**Comment by Theuns-Botha** [comment]
No longer relevant

**Pull request closed without merging**
